# 편미분 구현

In [ ]:
import numpy as np

## 01. 기본 미분

In [ ]:
def simple_numerical_diff(f, x):
  h = 10e-4
  diff = (f(x+h) - f(x-h)) / 2*h
  return diff

def func1(x):
  return x*x

In [ ]:
f = func1
simple_numerical_diff(f, 2.0)

3.999999999999559e-06

## 02. 편미분

In [ ]:
def func2(W):

  x = W[0]
  y = W[1]

  return (2*x + 3*x*y + np.power(y,3))

def func3(x):

  result = 0
  for idx in range(x.size):
    result += x[idx]**2

  return result

def numerical_diff(f, x):
  h = 1e-5
  grad = np.zeros_like(x)

  for idx in range(x.size):
    temp_val = float(x[idx])

    x[idx] = temp_val + h
    y_f = f(x)

    x[idx] = temp_val - h
    y_b = f(x)

    grad[idx] = (y_f - y_b) / (2*h)
    x[idx] = temp_val
    
  return grad  

In [ ]:
f2 = func2
variables = [1.0, 2.0]
np_variables = np.array(variables)

In [ ]:
np_variables

array([1., 2.])

In [ ]:
numerical_diff(f2, np_variables)

array([ 8., 15.])

In [ ]:
f3 = func3
variables = [1.0, 2.0, 3.0]
np_variables = np.array(variables)

In [ ]:
numerical_diff(f3, np_variables)

array([2., 4., 6.])