# Multi-Variable 2차원 이상의 Parameter 미분함수 구현하기

 - 가설함수 $f = w_1*x_1 + w_2*x_2 + b$

In [1]:
import numpy as np

In [22]:
x_data = np.array([[1.0, 2.0], 
                   [2.0, 4.0], 
                   [3.0, 9.0]])

In [23]:
W = np.random.rand(1,2)
b = np.random.rand(1)

In [24]:
W

array([[0.89566489, 0.65430024]])

In [25]:
def func1(X):
  return np.dot(W, X.transpose()) + b

In [26]:
func1(x_data)

array([[2.24157885, 4.44584422, 8.61301031]])

In [45]:
W.shape

(1, 2)

In [32]:
def numerical_diff(f, X):
  h = 1e-4
  grad = np.zeros_like(X)
  print(grad)

  vec1_dim = X.shape[0], vec2_dim = X.shape[1] 
  for x_idx in range(vec1_dim):
    for y_idx in range(vec2_dim):
      temp_value = X[x_idx, y_idx]
      X[x_idx, y_idx] = temp_value + h
      f_f = f(X)

      X[x_idx, y_idx] = temp_value - h
      f_b = f(X)

      grad[x_idx, y_idx] = (f_f - f_b) / (2*h)
      X[x_idx, y_idx] = temp_value

  return grad

In [33]:
f = func1

In [46]:
W

array([[0.89566489, 0.65430024]])

In [47]:
delta_x = 1e-4 # 0.0001
grad = np.zeros_like(W)

it = np.nditer(W, flags=['multi_index'], op_flags=['readwrite'])

In [49]:
it.finished

False

In [50]:
while not it.finished:
    idx = it.multi_index        
    tmp_val = W[idx] W[0,0]
    print(idx)
    it.iternext()  

(0, 0)
(0, 1)


In [34]:
numerical_diff(f, x_data)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


ValueError: ignored