In [12]:
import numpy as np
import random
import pandas as pd

In [2]:
x_data = [[0,0],[0,1],[1,0],[1,1]]
t_data = [[0],[1],[1],[0]]
x_data = np.array(x_data)
t_data = np.array(t_data)
#t_data = [0,1,1,0]

In [3]:
W2 = np.random.rand(2,6)
b2 = np.random.rand(6)
W3 = np.random.rand(6,1)
b3 = np.random.rand(1)

In [4]:
def sigmoid(z):
  return 1 / (1+np.exp(-z)) 

def bce(X, target):
  delta = 1e-8
  z2 = np.dot(X,W2)+b2
  a2 = sigmoid(z2)

  z3 = np.dot(a2,W3)+b3
  a3 = sigmoid(z3)

  return -np.sum(target*np.log(a3+delta) + (1-target) * np.log((1-a3)+delta))


In [5]:
bce(x_data, t_data)

4.952214660143075

In [6]:
# 수치미분 함수
def numerical_derivative(f, x):
    delta_x = 1e-4 # 0.0001
    grad = np.zeros_like(x)
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx = it.multi_index        
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x) # f(x+delta_x)
        
        x[idx] = tmp_val - delta_x 
        fx2 = f(x) # f(x-delta_x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        x[idx] = tmp_val 
        it.iternext()   
        
    return grad

In [7]:
bceF = lambda x: bce(x_data, t_data)

In [9]:
learning_rate = 0.1
for idx in range(1000):

  W2_grad = numerical_derivative(bceF, W2)
  b2_grad = numerical_derivative(bceF, b2)
  W3_grad = numerical_derivative(bceF, W3)
  b3_grad = numerical_derivative(bceF, b3)

  W2 = W2 - learning_rate*W2_grad
  b2 = b2 - learning_rate*b2_grad
  W3 = W3 - learning_rate*W3_grad
  b3 = b3 - learning_rate*b3_grad

  loss = bce(x_data, t_data)
  print("LOSS: ", loss, "W2: ", W2, "W3: ", W3)

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
 [-0.01345599]
 [ 0.04299471]]
LOSS:  2.7626828319293044 W2:  [[ 0.87802339  0.83073136 -0.12643136  0.53694423  0.81661121  0.21358673]
 [-0.19055539  0.43518272  0.60773186  0.2408052   0.04332843  0.57888146]] W3:  [[-0.28539445]
 [ 0.45134496]
 [-0.36335956]
 [-0.07289059]
 [-0.01362892]
 [ 0.04337128]]
LOSS:  2.7625944380072665 W2:  [[ 0.87829676  0.83159738 -0.12710386  0.53689221  0.81661106  0.2136961 ]
 [-0.19171544  0.4369035   0.60794889  0.24068126  0.04329313  0.5789255 ]] W3:  [[-0.28644904]
 [ 0.45257694]
 [-0.3637479 ]
 [-0.07278023]
 [-0.01380245]
 [ 0.04374732]]
LOSS:  2.762505267240949 W2:  [[ 0.87857276  0.8324693  -0.12777676  0.53684034  0.81661093  0.21380641]
 [-0.19287958  0.43863099  0.6081678   0.24055768  0.0432574   0.57896989]] W3:  [[-0.28750865]
 [ 0.4538164 ]
 [-0.36413848]
 [-0.07267084]
 [-0.01397658]
 [ 0.04412281]]
LOSS:  2.7624153111901895 W2:  [[ 0.8788514   0.83334715 -0.12845005  0.53678864  0.8166108   0.2139

In [10]:
def predict(X):
  z2 = np.dot(X,W2)+b2
  a2 = sigmoid(z2)

  z3 = np.dot(a2,W3)+b3
  a3 = sigmoid(z3)
  return a3

In [11]:
predict(np.array([1,1]))

array([0.28248606])